### ISSUE TITLE
ivtools: abs() compile error with gcc 6

### ISSUE THREAD

**Issue by AdrianBunk** [vectaport/ivtools-1.2#5]
http://bugs.debian.org/835747

Source used in Debian: https://sources.debian.net/src/ivtools/1.2.11a1-7/

Relevant gcc change: http://gcc.gnu.org/gcc-6/porting_to.html

It seems you were wrongly expecting to get a signed result from the subtraction.

**Comment by barak** [comment]
there are also some zero-comparison errors, i'm going through scrubbing them now should a fix pushed and a pull request generated in reasonably short order

**Comment by barak** [comment]
Fixed on in my fork, barak/tweaks or barak/tweaks1 which is the same but rebased for ease of examination. See in particular 9741bca 5dd153e or b56be32 23a358d which are already uploaded to Debian to close 835747.

**Comment by vectaport** [comment]
Verified these changes have propagated upstream.
